config/routes.rb
Rails.application.routes.draw do

  get 'categories' => 'categories#index', as: :main
  get '/categories/new' => 'categories#new'
  post '/categories' => 'categories#create'
  get '/categories/:id' => 'categories#show', as: :category

  get '/subcategories/new/:id' => 'subcategories#new', as: :newsubcategory
  post '/subcategories/create/:id' => 'subcategories#create', as: :subcategories
  get '/subcategories/:id' => 'subcategories#show', as: :subcategory

  get '/subsubcategories/new/:id' => 'subsubcategories#new', as: :newsubsubcategory
  post '/subsubcategories/create/:id' => 'subsubcategories#create', as: :subsubcategories
  get '/subsubcategories/:id' => 'subsubcategories#show', as: :subsubcategory

  get '/procedures/new/:id' => 'procedures#new', as: :newprocedure
  post '/procedures/' => 'procedures#create'
  get '/procedures/:id' => 'procedures#show', as: :procedure

  get '/categories/:id/edit' => 'categories#edit', as: :edit_category
  patch '/categories/:id' => 'categories#update'

  get '/subcategories/:id/edit' => 'subcategories#edit', as: :edit_subcategory 
  patch '/subcategories/:id' => 'subcategories#update'

  get '/subsubcategories/:id/edit' => 'subsubcategories#edit', as: :edit_subsubcategory 
  patch '/subsubcategories/:id' => 'subsubcategories#update'

  get '/procedures/:id/edit' => 'procedures#edit', as: :edit_procedure
  patch '/procedures/:id' => 'procedures#update'

  patch '/procedures/note/:id' => 'procedures#updatenote'

  patch '/procedures/updatenote/:id' => 'procedures#addprocedure', as: :note

  get 'signup'  => 'users#new' 
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy', as: :logout

  delete 'categories/:id' => 'categories#destroy', as: :delete_category

  delete 'subcategories/:id' => 'subcategories#destroy', as: :delete_subcategory

  delete 'subsubcategories/:id' => 'subsubcategories#destroy', as: :delete_subsubcategory

  delete 'procedures/:id' => 'procedures#destroy', as: :delete_procedure

  post '/ajax/sum' => 'categories#ajax_sum'

 

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	belongs_to :category
	has_many :sub_sub_category
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :subsubcategories
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController

	before_action :require_user, only: [:index, :show, :edit]
	
	def show
		@subcategory = Subcategory.find(params[:id])
		@subsubcategories = @subcategory.subsubcategories.all
		@thisid = params[:id]

		@previousid = params[@subcategory.category]
		# if @subcategory[0].category_id == nil
		# 	@subcategory[0].category_id = 1
		# end
		# @previousid = @subcategory[1].category_id
	end

	def edit 
	  @subcategory = Subcategory.find(params[:id]) 
	end

	def update 
	  @subcategory = Subcategory.find(params[:id]) 
	  if @subcategory.update_attributes(subcategory_params) 
	   redirect_to(category_path(:id => @subcategory.category_id)) 
 
	  else 
	    render 'edit' 
	  end 
	end

	def new
		@subcategory = Subcategory.new(category_id: params[:id])
	end

	def create
		#@category = Category.find(params[:id])
		@thisid = params[:id]
		@subcategory = Subcategory.new(subcategory_params)
		#@subcategory.category_id = params[:id]
		#@subcategory = Subcategory.create(category_id: params[:id])


		if @subcategory.save
			redirect_to(category_path(:id => @subcategory.category_id))
		else
			render 'new'
		end
	end

	def destroy
		@previd = Subcategory.find(params[:id])
		Subcategory.find(params[:id]).destroy
		flash[:success] = "Subcategory deleted"
		redirect_to(category_path(@previd.category_id))
	end

	private
		def subcategory_params
			params.require(:subcategory).permit(:title, :category_id)
		end

end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/edit.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">


    <%= form_for(@subcategory) do |f| %>
      <%= f.label :subcategory %>
      <%= f.text_field :title %>
      <%= f.submit "Update", :class => "btn" %>
    <% end %> 
    
  </div>
</div> 

app/views/subcategories/new.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg">
    <h1>Messenger</h1>
  </div>
</div>

<div class="create">
  <div class="container">
    
    <!-- Your code here -->
    <%= form_for(@subcategory) do |f| %>  
      <div class="field"> 
        <%= f.label :subcategory %><br> 
        <%= f.text_area :title %> 
      </div> 
      <div class="actions"> 
        <%= f.submit "Create" %> 
      </div> 
    <% end %>
    
  </div>
</div>

app/views/subcategories/show.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    	
      <div class="card col-xs-4">
        <h2><%= @subcategory.title %></h2>

        <% @subsubcategories.each do |sc| %>
        <p><%= sc.title %></p>

              <%= link_to "See More", subsubcategory_path(sc) %>
              <% if current_user && current_user.admin? %> 
                <br>
                <%= link_to "Edit", edit_subsubcategory_path(sc) %>
                <%= link_to "Delete", delete_subsubcategory_path(sc), method: "delete", data: { confirm: "You sure?" } %>
              <% end %>
              <br><br>


        <% end %>

      </div>
      <br><br>
      <% if current_user && current_user.admin? %> 
      <%= link_to "Add a new Subsubcategory", newsubsubcategory_path(), :id=> @thisid %>
      <br>
      <br>
      <% end %>
      <%= link_to "Back", category_path(:id => @subcategory.category_id) %>
     <br><br>
      <%= link_to "Back to Home Page", main_path() %>
    </div>
  </div>
</div>