config/routes.rb
Rails.application.routes.draw do

  get 'categories' => 'categories#index', as: :main
  get '/categories/new' => 'categories#new'
  post '/categories' => 'categories#create'
  get '/categories/:id' => 'categories#show', as: :category

  get '/subcategories/new/:id' => 'subcategories#new', as: :newsubcategory
  post '/subcategories/create/:id' => 'subcategories#create', as: :subcategories
  get '/subcategories/:id' => 'subcategories#show', as: :subcategory

  get '/subsubcategories/new/:id' => 'subsubcategories#new', as: :newsubsubcategory
  post '/subsubcategories/create/:id' => 'subsubcategories#create', as: :subsubcategories
  get '/subsubcategories/:id' => 'subsubcategories#show', as: :subsubcategory

  get '/procedures/new/:id' => 'procedures#new', as: :newprocedure
  post '/procedures/' => 'procedures#create'
  get '/procedures/:id' => 'procedures#show', as: :procedure

  get '/categories/:id/edit' => 'categories#edit', as: :edit_category
  patch '/categories/:id' => 'categories#update'

  get '/subcategories/:id/edit' => 'subcategories#edit', as: :edit_subcategory 
  patch '/subcategories/:id' => 'subcategories#update'

  get '/subsubcategories/:id/edit' => 'subsubcategories#edit', as: :edit_subsubcategory 
  patch '/subsubcategories/:id' => 'subsubcategories#update'

  get '/procedures/:id/edit' => 'procedures#edit', as: :edit_procedure
  patch '/procedures/:id' => 'procedures#update'

  patch '/procedures/note/:id' => 'procedures#updatenote'

  patch '/procedures/updatenote/:id' => 'procedures#addprocedure', as: :note

  get 'signup'  => 'users#new' 
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy', as: :logout

  delete 'categories/:id' => 'categories#destroy', as: :delete_category

  delete 'subcategories/:id' => 'subcategories#destroy', as: :delete_subcategory

  delete 'subsubcategories/:id' => 'subsubcategories#destroy', as: :delete_subsubcategory

  delete 'procedures/:id' => 'procedures#destroy', as: :delete_procedure

  post '/ajax/sum' => 'categories#ajax_sum'

 

end

app/models/sub_sub_category.rb
class SubSubCategory < ActiveRecord::Base
	belongs_to :sub_category
end

app/models/subsubcategory.rb
class Subsubcategory < ActiveRecord::Base
	belongs_to :subcategory
	has_many :procedures
end

app/controllers/subsubcategories_controller.rb
class SubsubcategoriesController < ApplicationController

	before_action :require_user, only: [:index, :show, :edit]
	
	def show
		@subsubcategory = Subsubcategory.find(params[:id])
		@procedures = @subsubcategory.procedures
		@thisid = params[:id]
	end

	def new
		@subsubcategory = Subsubcategory.new(subcategory_id: params[:id])
	end

	def edit 
	  @subsubcategory = Subsubcategory.find(params[:id]) 
	end

	def update 
	  @subsubcategory = Subsubcategory.find(params[:id]) 
	  if @subsubcategory.update_attributes(subsubcategory_params) 
	    redirect_to(subcategory_path(:id => @subsubcategory.subcategory_id)) 
	  else 
	    render 'edit' 
	  end 
	end

	def create
		#@category = Category.find(params[:id])
		@thisid = params[:id]
		@subsubcategory = Subsubcategory.new(subsubcategory_params)
		#@subcategory.category_id = params[:id]
		#@subcategory = Subcategory.create(category_id: params[:id])


		if @subsubcategory.save
			redirect_to(subcategory_path(:id => @subsubcategory.subcategory_id))
		else
			render 'new'
		end
	end

	def destroy
		@previd = Subsubcategory.find(params[:id])
		Subsubcategory.find(params[:id]).destroy
		flash[:success] = "Subsubcategory deleted"
		redirect_to(subcategory_path(@previd.subcategory_id))
	end

	private
		def subsubcategory_params
			params.require(:subsubcategory).permit(:title, :subcategory_id)
		end

end

app/helpers/subsubcategories_helper.rb
module SubsubcategoriesHelper
end

app/views/subsubcategories/edit.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">


    <%= form_for(@subsubcategory) do |f| %>
      <%= f.label :subsubcategory %>
      <%= f.text_field :title %>
      <%= f.submit "Update", :class => "btn" %>
    <% end %> 
    
  </div>
</div> 

app/views/subsubcategories/new.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg">
    <h1>Messenger</h1>
  </div>
</div>

<div class="create">
  <div class="container">
    
    <!-- Your code here -->
   <%= form_for(@subsubcategory) do |f| %>  
      <div class="field"> 
        <%= f.label :subsubcategory %><br> 
        <%= f.text_area :title %>
        <%= f.text_area :subcategory_id %>
      </div> 
      <div class="actions"> 
        <%= f.submit "Create" %> 
      </div> 
    <% end %> 
    
  </div>
</div>

app/views/subsubcategories/show.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    	
      <div class="card col-xs-4">
        <h2><%= @subsubcategory.title %></h2>
        
        <% @procedures.each do |sc| %><br>
        <%= sc.content %>
        <br>
        <%= link_to "Add to Doc", procedure_path(sc) %>
        <% if current_user && current_user.admin? %> 
        <br>
        <%= link_to "Edit", edit_procedure_path(sc) %>
        <%= link_to "Delete", delete_procedure_path(sc), method: "delete", data: { confirm: "You sure?" } %>
        <% end %>
        <br><br>
        

        <% end %>

      </div>
      <br><br>
      <%= link_to "Back", subcategory_path(:id => @subsubcategory.subcategory_id) %><br><br>
      <% if current_user && current_user.admin? %> 
      <%= link_to 'Add New Procedure', newprocedure_path(), :id=> @thisid %>
      <% end %>
      <br><br>
      <%= link_to "Back to Home Page", main_path() %>
     
    </div>
  </div>
</div>