config/routes.rb
Rails.application.routes.draw do

  get 'categories' => 'categories#index', as: :main
  get '/categories/new' => 'categories#new'
  post '/categories' => 'categories#create'
  get '/categories/:id' => 'categories#show', as: :category

  get '/subcategories/new/:id' => 'subcategories#new', as: :newsubcategory
  post '/subcategories/create/:id' => 'subcategories#create', as: :subcategories
  get '/subcategories/:id' => 'subcategories#show', as: :subcategory

  get '/subsubcategories/new/:id' => 'subsubcategories#new', as: :newsubsubcategory
  post '/subsubcategories/create/:id' => 'subsubcategories#create', as: :subsubcategories
  get '/subsubcategories/:id' => 'subsubcategories#show', as: :subsubcategory

  get '/procedures/new/:id' => 'procedures#new', as: :newprocedure
  post '/procedures/' => 'procedures#create'
  get '/procedures/:id' => 'procedures#show', as: :procedure

  get '/categories/:id/edit' => 'categories#edit', as: :edit_category
  patch '/categories/:id' => 'categories#update'

  get '/subcategories/:id/edit' => 'subcategories#edit', as: :edit_subcategory 
  patch '/subcategories/:id' => 'subcategories#update'

  get '/subsubcategories/:id/edit' => 'subsubcategories#edit', as: :edit_subsubcategory 
  patch '/subsubcategories/:id' => 'subsubcategories#update'

  get '/procedures/:id/edit' => 'procedures#edit', as: :edit_procedure
  patch '/procedures/:id' => 'procedures#update'

  patch '/procedures/note/:id' => 'procedures#updatenote'

  patch '/procedures/updatenote/:id' => 'procedures#addprocedure', as: :note

  get 'signup'  => 'users#new' 
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy', as: :logout

  delete 'categories/:id' => 'categories#destroy', as: :delete_category

  delete 'subcategories/:id' => 'subcategories#destroy', as: :delete_subcategory

  delete 'subsubcategories/:id' => 'subsubcategories#destroy', as: :delete_subsubcategory

  delete 'procedures/:id' => 'procedures#destroy', as: :delete_procedure

  post '/ajax/sum' => 'categories#ajax_sum'

 

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	
	before_action :require_user, only: [:show, :edit, :update, :destroy]
  	before_action :require_editor, only: [:show, :edit]
  	before_action :require_admin, only: [:destroy]

 
	
	def index
		@categories = Category.all

		@note = Note.find_by(id: '1')


		
	


	end


	def write_to_file
		path = "../Notes/Note.txt"
		content = "data from the form"
		File.open(path, "w+") do |f|
		  f.write(content)
		end
	end




	def edit
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
		@subcategories = @category.subcategories
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to '/categories'
		else
			render 'new'
		end
	end


	def update 
	  @category = Category.find(params[:id]) 
	  if @category.update_attributes(category_params) 
	    redirect_to(main_path()) 
	  else 
	    render 'edit' 
	  end 
	end

	def destroy
		Category.find(params[:id]).destroy
		flash[:success] = "Category deleted"
		redirect_to(main_path())
	end

	def writetofile
		@note = Note.find_by(id: '1')
		@file_data = @note.last_name + ', ' + @note.first_name + "\n\n\n" + @note.technique
		@file_name = @note.last_name + ', ' + @note.first_name
		p @file_data
		p @file_name
		# send_data(@file_data, options = {:filename => @file_name})
		File.write('/Note/file', @file_data)
		flash[:success] = @file_name + ' was saved'
	end

	helper_method :writetofile

	def ajax_sum
        @note = Note.find_by(id: '1')
		@file_data = @note.last_name + ', ' + @note.first_name + "\n\n" + @note.technique
		@file_name = @note.last_name + ', ' + @note.first_name
		# p @file_data
		# p @file_name
		# send_data(@file_data.note.path, options = {:filename => @file_name, :type => 'text', :x_sendfile => true})
		# p 'sent'
		File.write('./Notes/' + @file_name + ".txt", @file_data)
		flash[:success] = @file_name + ' was saved'

		send_file('/Notes/' + @file_name + '.txt', options = {:filename => @file_name, :type => 'txt', :x_sendfile => true})
    end


	private
		def category_params
			params.require(:category).permit(:title)
		end




end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">


    <%= form_for(@category) do |f| %>
      <%= f.label :category %>
      <%= f.text_field :title %>
      <%= f.submit "Update", :class => "btn" %>
    <% end %> 
    
  </div>
</div> 

app/views/categories/index.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    	<% @categories.each do |t| %>
      <div class="card col-xs-4">
        <h2><%= t.title %></h2>
        <%= link_to "Learn more", category_path(t) %>
        <% if current_user && current_user.admin? %> 
          <%= link_to "Edit", edit_category_path(t) %>
          <%= link_to "Delete", delete_category_path(t), method: "delete", data: { confirm: "You sure?" } %>
        <% end %>
      </div>
      <% end %>
      <br>
      <% if current_user && current_user.admin? %> 
      <%= link_to 'Add New Category', "categories/new" %>
      <% end %>

      <br><br>
      <%= form_for(@note) do |f| %>

      <%= f.text_field :last_name, :placeholder => "Last Name" %>
      <%= f.text_field :first_name, :placeholder => "First Name" %>
      <%= f.text_area :technique, :placeholder => "Put your notes here here", :class => "main_doc" %>
      <%= f.submit "Update", :class => "btn" %>

      <%= button_to 'Write Write', '#', :onclick => 'sum_fn()' %>
      <%= javascript_tag do %>
          function sum_fn() {
              /* Assuming you have jQuery */
              $.post('/ajax/sum.json', {
                   num1: 100,
                   num2: 50
              }, function(data) {
                   var output = data.result;
                   /* output should be 150 if successful */
              });
          }
      <% end %>

    <% end %> 
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg">
    <h1>Messenger</h1>
  </div>
</div>

<div class="create">
  <div class="container">
    
    <!-- Your code here -->
    <%= form_for(@category) do |f| %>  
      <div class="field"> 
        <%= f.label :category %><br> 
        <%= f.text_area :title %> 
      </div> 
      <div class="actions"> 
        <%= f.submit "Create" %> 
      </div> 
    <% end %>
    
  </div>
</div>

app/views/categories/show.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tags">
  <div class="container">

    <div class="cards row">
    	
      <div class="card col-xs-4">

        <h2><%= @category.title %></h2>


        <% @subcategories.each do |sc| %>
        <p><%= sc.title %></p>
              <%= link_to "See More", subcategory_path(sc) %>
              <% if current_user && current_user.admin? %> 
              <br>
              <%= link_to "Edit", edit_subcategory_path(sc) %>
              <%= link_to "Delete", delete_subcategory_path(sc), method: "delete", data: { confirm: "You sure?" } %>

              <% end %>
              <br><br>
        
        <% end %>
        
      </div>
      
      <%= link_to "Back", main_path() %><br><br>
      <% if current_user && current_user.admin? %> 
      <%= link_to 'Add New Subcategory', newsubcategory_path(), :id=> @thisid %>
      <% end %>


    </div>
  </div>
</div>